### ISSUE TITLE
migrate DNS domain from storm3 to IPA

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/automation#47]
TODO: need to find existing forward config from inf1 to storm3

**Comment by rbo** [comment]
@DanielFroehlich I changed the forwarders from 10.32.105.3 to  10.32.96.1; 10.32.96.31; at ocp4support VM


Does more stormshift related dns servers still use storm3 as dns? Maybe we should start the named again and forward everything to inf1/inf31 ?

**Comment by rbo** [comment]
PS.: I was looking for the issue in support repo first...

**Comment by rbo** [comment]
IMHO this should only related to automation/ansible/aap and not to lab infrastructure.

**Comment by DanielFroehlich** [comment]
thanks for fixing it! No, I am not aware of any other forwarders. Its only the very special UPI bastion setup of OCP4 from before IPI days. 
I would like to keep the DNS on storm3 down, to really find all remaining usages so that the move is final.
And sorry for the confusion, i did not wanted to spam the support repo with all my migration project cases.
